version: '3.1'

services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./certs/master.local.key:/etc/ssl/private/master.local.key"
      - "./certs/master.local.crt:/etc/ssl/certs/master.local.bundle.crt"
    depends_on:
      - docker-registry
      - registry-ui

  docker-registry:
    image: registry:2.7.1
    volumes:
      - registry-data:/var/lib/registry

  registry-ui:
    image: quiq/docker-registry-ui
    ports:
      - 8000:8000
    volumes:
      - "./config.yml:/opt/config.yml"
    depends_on:
      - docker-registry

volumes:
  registry-data:
    driver: local