apiVersion: v1
data:
  nginx.conf: |-
    worker_processes 1;

    events {
        worker_connections 1024;
        use epoll;
    }

    http {

        server {
            listen 443 ssl http2 default_server;
            listen [::]:443 ssl http2 default_server;
            ssl_certificate /etc/ssl/certs/master.local.bundle.crt;
            ssl_certificate_key /etc/ssl/private/master.local.key;

            client_max_body_size 0;

            location / {
                proxy_pass http://registry:5000;
            }

            location /v2/ {
                # Do not allow connections from docker 1.5 and earlier
                # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
                # if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
                #    return 404;
                #}

                # To add basic authentication to v2 use auth_basic setting.
                #auth_basic "Registry realm";
                #auth_basic_user_file /etc/nginx/conf.d/nginx.htpasswd;

                ## If $docker_distribution_api_version is empty, the header is not added.
                ## See the map directive above where this variable is defined.
                # add_header 'Docker-Distribution-Api-Version' $docker_distribution_api_version always;

                proxy_pass                          http://registry:5000;
                proxy_set_header  Host              $http_host;   # required for docker client's sake
                proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
                proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto  $scheme;
                proxy_set_header X-Forwarded-Host   $host:$server_port;
                proxy_set_header X-Original-URI     $request_uri;
                proxy_set_header Docker-Distribution-Api-Version registry/2.0;
                proxy_read_timeout                  900;
            }

            location /ui {
                proxy_pass http://registry-ui:8000;
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-conf
  namespace: docker-registry
