apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: registry
  name: registry
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: registry
    spec:
      containers:
      - image: registry:2.7.1
        name: registry
        resources: {}
        volumeMounts:
        - name: data
          mountPath: /var/lib/registry/
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nfs-registry-pvc
status: {}