apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-registry-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.103  # Replace Me!
    path: "/mnt/usb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-registry-pvc
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi