apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: registry-ui
  name: registry-ui
  namespace: docker-registry
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: registry-ui
  type: ClusterIP
status:
  loadBalancer: {}