apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: docker-registry
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 30080
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}